name: SonarQube Analysis

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub automatically handles the Node.js upgrade

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # This will automatically use Node.js 20 when available
      with:
        java-version: '11'

    - name: Cache SonarQube scanner
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Run SonarQube analysis
      run: |
        ./gradlew sonar \
        -Dsonar.host.url=http://localhost:9997 \  # Connects to your SonarQube running locally
        -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \  # SonarQube token for authentication
        -Dsonar.projectKey=Github-Sonar-Integrations \  # Replace with your actual project key
        -Dsonar.projectName=Github-Sonar-Integrations  # Replace with your desired project name
