name: SonarCloud Analysis

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17  # Use Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Change to Java 17
        distribution: 'temurin'

    - name: Cache SonarQube scanner
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run SonarCloud analysis
      run: |
        ./gradlew sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=${{ secrets.SONAR_ORG }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
        -Dsonar.projectName=ExampleSonarScannerGradle
