name: SonarQube Analysis

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub automatically handles the Node.js upgrade

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify the JDK distribution (temurin, zulu, or adopt)

    - name: Cache SonarQube scanner
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Run SonarQube analysis
      working-directory: ./path-to-your-gradle-project  # Set the working directory if gradlew is not in the root
      run: |
        ./gradlew sonar \
        -Dsonar.host.url=http://localhost:9997 \
        -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
        -Dsonar.projectKey=Github-Sonar-Integrations \
        -Dsonar.projectName=Github-Sonar-Integrations
